# Generated by Django 5.0.4 on 2024-04-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('category', models.CharField(choices=[('R', 'Rice'), ('N', 'Noodles'), ('S', 'Soup'), ('C', 'Chicken'), ('x', 'Side')], default='R', max_length=1)),
                ('note', models.CharField(max_length=256)),
            ],
        ),
    ]
