# Generated by Django 5.0.4 on 2024-04-16 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main_app.menu'),
            preserve_default=False,
        ),
    ]
