# Generated by Django 5.0.4 on 2024-04-16 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_photo_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='cat',
        ),
    ]
